### ISSUE TITLE
Can't open Developer Portal page - Docker

### ISSUE THREAD

**Issue by Sharathmk99** [yoanisgil/tyk_quickstart#3]
I installed tyk from docker compose. I can open Tyk.io Gateway page but i'm not able to open Developer Portal using link http://test-api.testorg.docker:8888/portal/
It says server not found.
I followed below tutorial
https://tyk.io/v1.8/setup/docker/

Thanks

**Comment by yoanisgil** [comment]
@Sharathmk99 I just went through this setup https://tyk.io/v1.9/setup/docker/ and everything works as expected.

**Comment by yoanisgil** [comment]
Closing this issue as it's been +2 months. @Sharathmk99 feel happen to reopen if you still face this issue.
