### ISSUE TITLE
setup.sh leads to an error on OSX 10.11.2

### ISSUE THREAD

**Issue by yoanisgil** [yoanisgil/tyk_quickstart#5]
This command (from this line https://github.com/yoanisgil/tyk_quickstart/blob/master/setup.sh#L14) leads to an error

```
$ TYK_DASHBOARD_USERNAME=$(env LC_CTYPE=C tr -dc "a-z0-9" < /dev/urandom | head -c 10)"@test.com"
 tr: Illegal byte sequence
```

I'm not entirely sure why but I was wondering if we could just do something like:

TYK_DASHBOARD_USERNAME=test@test.com

or if we really need this to be random we can do something like:

TYK_DASHBOARD_USERNAME="test$RANDOM@test.com" which is a standard bash feature.

@lonelycode @JosephEarl thoughts?

**Comment by josephearl** [comment]
Yes I actually think setting it something predictable is better (and is what I use in my own scripts) because if you're testing and continuously rebuilding the environment it is a pain to keep having to copy and paste the new email when logging in.

**Comment by lonelycode** [comment]
The reason it's random is to prevent duplicates in the MongoDB so that it can be re-used and re-run over and over again easily (which happens a lot with new users)

**Comment by yoanisgil** [comment]
Something like this should do right?

https://github.com/yoanisgil/tyk_quickstart/commit/7927152ec1553b9cb827f4f14b0a1230af527f8f

**Comment by lonelycode** [comment]
Yup that should be fine - want to PR it?

**Comment by yoanisgil** [comment]
Done here https://github.com/lonelycode/tyk_quickstart/pull/2. I'm a bit loss with the fork history but hopefully it should be alright ;)

**Comment by lonelycode** [comment]
Sweet, merged - thanks!

**Comment by yoanisgil** [comment]
Closing as it's been merged here https://github.com/lonelycode/tyk_quickstart/pull/2
