### ISSUE TITLE
Docker with Tyk 2.0

### ISSUE THREAD

**Issue by matiasinsaurralde** [yoanisgil/tyk_quickstart#7]
Is it possible to use this `docker-compose.yml` with Tyk 2?

I'm getting errors like:
`Unsupported config option for services service: 'tyk_mongo'`

Best regards!

**Comment by yoanisgil** [comment]
Check this one:

https://github.com/lonelycode/tyk_quickstart

event though I started the project Tyk's author forked it and that should be the main reference ;).
